[package]
name = "karst/aow"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
knit = "sleitnick/knit@1.7.0"
janitor = "howmanysmall/janitor@1.18.3"


[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"